import "./globals.css";

import NavBar from "./components/NavBar";
import LayoutFooter from "./components/LayoutFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <NavBar />
        {children}
        <LayoutFooter />
      </body>
    </html>
  );
}
